//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FilmBox_DbEntities : DbContext
    {
        public FilmBox_DbEntities()
            : base("name=FilmBox_DbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Actor> Actors { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Director> Directors { get; set; }
        public virtual DbSet<Film> Films { get; set; }
        public virtual DbSet<FilmActorDetail> FilmActorDetails { get; set; }
        public virtual DbSet<FilmCategoryDetail> FilmCategoryDetails { get; set; }
        public virtual DbSet<FilmCustomerDetail> FilmCustomerDetails { get; set; }
        public virtual DbSet<FilmDirectorDetail> FilmDirectorDetails { get; set; }
        public virtual DbSet<Series> Series { get; set; }
        public virtual DbSet<SeriesActorDetail> SeriesActorDetails { get; set; }
        public virtual DbSet<SeriesCategoryDetail> SeriesCategoryDetails { get; set; }
        public virtual DbSet<SeriesCustomerDetail> SeriesCustomerDetails { get; set; }
        public virtual DbSet<SeriesDirectorDetail> SeriesDirectorDetails { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
